name: mio_ding
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  get_it: ^7.2.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  go_router: ^13.0.0
  freezed_annotation: ^2.4.1
  injectable: ^2.1.2
  provider: ^6.0.5
  image_picker: ^1.0.4
  speech_to_text: ^6.3.0
  cached_network_image: ^3.2.3
  mysql1: ^0.20.0
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.5
  injectable_generator: ^2.1.6
  mockito: ^5.4.4
  analyzer: ^5.13.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - .env.development
    - .env.production
    - web/assets/.env
    - assets/images/
    - assets/icons/