name: mio_ding
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  go_router: ^13.0.0
  provider: ^6.1.1
  image_picker: ^1.0.7
  speech_to_text: ^6.6.0
  cached_network_image: ^3.3.1
  google_fonts: ^6.1.0
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  analyzer: ^6.4.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - .env.development
    - .env.production
    - web/assets/.env
    - assets/images/
    - assets/icons/